apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: us-west1-docker.pkg.dev/qwiklabs-gcp-03-c8ad5dd5046d/my-repository/hello-cloudbuild-dev
        ports:
        - containerPort: 8080
